---
- import_playbook: hosts.yml

- hosts: prodbdd
  roles:
    - mysql
  vars:
    ansible_become_password: "{{ root_password }}"
  tags: bdd

- hosts: prodapp
  roles:
    - app
  vars:
    ansible_become_password: "{{ root_password }}"
  tags: app

- hosts: prodfront
  roles:
    - front
  vars:
    ansible_become_password: "{{ root_password }}"
  tags: front
