app_deploy_user: ansible
app_deploy_source: "roles/app/files/backend.zip"
app_deploy_destination: /APP

node_node_version: 10.17.0
app_node_executable: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_node_version }}/bin"

angular_angular_npm_path: "{{ app_node_executable }}"

deploy_deploy_user: "{{ app_deploy_user }}"
deploy_deploy_source: "{{ app_deploy_source }}"
deploy_deploy_destination: "{{ app_deploy_destination }}"
deploy_build_dir: "{{ app_deploy_destination }}/back"

build_build_dir: "{{ app_deploy_destination }}/back"

service__user: "{{ app_deploy_user }}"
service__name: "lavarel"
service__description: "Lavarel back"

service_install_directory: /APP/service/
service_install_start_exec_src: "roles/app/files/start_service.sh"
service_install_start_exec: "/APP/service/start_service.sh"

app_configure_env: "{{ build_build_dir }}/.env"
app_configure_src_env: "{{ app_configure_env }}.example"
