- name: role_front > Run yarn install
  command: yarn install
  args:
    chdir: "{{ deploy_deploy_destination }}/front/"
  tags:
  - front

- name: role_front > Run ng build
  command: ng build --prod
  args:
    chdir: "{{ deploy_deploy_destination }}/front/"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.nvm/versions/node/v{{ front_node_version }}/bin/"
  tags:
  - front
