- name: role_front > Create the DEST directory
  file:
    path: "{{ front_deploy_destination }}"
    state: directory
    owner: "{{ front_deploy_user }}"
    group: "{{ front_deploy_user }}"
  become: true
  become_method: su

- name: role_front > Deploy the front
  unarchive:
    src: "{{ front_deploy_source }}"
    dest: "{{ front_deploy_destination }}"

- name: role_front > Run npm install
  command: npm install
  args:
    chdir: "{{ front_deploy_destination }}/front/"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.nvm/versions/node/v{{ front_node_version }}/bin"

- name: role_front > Run ng build
  command: ng build --prod
  args:
    chdir: "{{ front_deploy_destination }}/front/"
