- name: role_front > Create the DEST directory
  file:
    path: "{{ front_deploy_destination }}"
    state: directory
    owner: "{{ front_deploy_user }}"
    group: "{{ front_deploy_user }}"
  become: true
  become_method: su
  tags:
  - setup
  - front
  - install

- name: role_front > Unzip the front
  unarchive:
    src: "{{ front_deploy_source }}"
    dest: "{{ front_deploy_destination }}"
  tags:
  - front

- name: role_front > Run yarn install
  command: yarn install
  args:
    chdir: "{{ front_deploy_destination }}/front/"
  tags:
  - front

- name: role_front > Run ng build
  command: ng build --prod
  args:
    chdir: "{{ front_deploy_destination }}/front/"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.nvm/versions/node/v{{ front_node_version }}/bin/"
  tags:
  - front
