- name: role_front > Create the ./nvm directory
  file:
    path: "{{ ansible_env.HOME }}/.nvm"
    state: directory

- name: frole_front > Get nvm script
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh
    dest: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    force: yes
    mode: '744'

- name: role_front > Install nvm
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh"
  args:
    executable: /bin/bash

- name: role_front > Install node version
  shell: "\\. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ front_node_version }}"
  args:
    executable: /bin/bash

- name: role_front > Use node version
  shell: "\\. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm use {{ front_node_version }}"
  args:
    executable: /bin/bash


- name: role_front > Install angular
  command: "npm install -g {{ front_node_angular }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.nvm/versions/node/v{{ front_node_version }}/bin"
