- name: role_front > Run ng serve
  command: ng serve
  args:
    chdir: "{{ front_deploy_destination }}/front/"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.nvm/versions/node/v{{ front_node_version }}/bin/"
  tags:
  - front
  - start
