- name: role_composer > ensure that composer and php are installed
  apt:
    name: "{{ composer_apt_packages }}"
    state: present
  become: true
  become_method: 'su'
  tags:
    - composer
    - install
