front_apt_packages:
  - 'unzip'
front_apt_yarn_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
front_node_angular: '@angular/cli'
front_node_angular_version: '7.1.4'
front_deploy_user: ansible
front_deploy_source: "{{ role_path }}/files/frontend.zip"
front_deploy_destination: /FRONT
