front_deploy_user: ansible
front_deploy_source: "roles/front/files/frontend.zip"
front_service_start_script: "roles/front/files/start_service.sh"
front_deploy_destination: /FRONT/
front_build_dir: "{{ front_deploy_destination }}front/"

node_node_version: 10.17.0
front_node_executable: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_node_version }}/bin"

angular_angular_npm_path: "{{ front_node_executable }}"

deploy_deploy_user: "{{ front_deploy_user }}"
deploy_deploy_source: "{{ front_deploy_source }}"
deploy_deploy_destination: "{{ front_deploy_destination }}"
deploy_build_dir: "{{ front_build_dir }}"

angular_build_dir: "{{ front_build_dir }}"
angular_build_ng_path: "{{ front_node_executable }}"

service__user: "{{ front_deploy_user }}"
service__name: "angular"
service__description: "Angular front"
service_install_directory: "{{ front_deploy_destination }}/service/"
service_install_start_exec_src: "{{ front_service_start_script }}"
service_install_start_exec: "{{ service_install_directory }}/start_service.sh"
