- name: role_node > ensure that apt prerequesites are installed
  apt:
    update_cache: yes
    name: "{{ node_apt_packages }}"
  become: true
  become_method: 'su'
  tags:
  - install
  - setup
  - node
