- name: role_node > Create the ./nvm directory
  file:
    path: "{{ ansible_env.HOME }}/.nvm"
    state: directory
  tags:
  - setup
  - install
  - node

- name: role_node > Get nvm script
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh
    dest: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    force: yes
    mode: '744'
  tags:
  - setup
  - install
  - node

- name: role_node > Install nvm
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh"
  args:
    executable: /bin/bash
  tags:
  - setup
  - install
  - node

- name: role_node > Install node version
  shell: "\\. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ node_node_version }}"
  args:
    executable: /bin/bash
  tags:
  - setup
  - install
  - node

- name: role_node > Use node version
  shell: "\\. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm use {{ node_node_version }}"
  args:
    executable: /bin/bash
  tags:
  - setup
  - install
  - node
