- name: role_lavarel > run yarn upgrade
  shell: yarn upgrade
  args:
    chdir: "{{ lavarel_build_dir }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ lavarel_build_node_exec }}"
  tags:
    - build

- name: role_lavarel > composer install
  composer:
    command: install
    working_dir: "{{ lavarel_build_dir }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ lavarel_build_node_exec }}"
  tags:
    - build
