- name: role_lavarel > create the .env file using .env.example
  copy:
    remote_src: yes
    src: "{{ lavarel_configure_env_src }}"
    dest: "{{ lavarel_configure_env }}"
    mode: '600'
  tags:
    - setup
    - configuration

- name: role_lavarel > configure the database host
  lineinfile:
    path: "{{ lavarel_configure_env }}"
    regexp: '^DB_HOST=.*$'
    line: "DB_PORT={{ lavarel_configure_db_host }}"
  tags:
    - setup
    - configuration

- name: role_lavarel > configure the database port
  lineinfile:
    path: "{{ lavarel_configure_env }}"
    regexp: '^DB_PORT=.*$'
    line: "DB_PORT={{ lavarel_configure_db_port }}"
  tags:
    - setup
    - configuration

- name: role_lavarel > configure the database name
  lineinfile:
    path: "{{ lavarel_configure_env }}"
    regexp: '^DB_DATABASE=.*$'
    line: "DB_PORT={{ lavarel_configure_db_name }}"
  tags:
    - setup
    - configuration

- name: role_lavarel > configure the database user
  lineinfile:
    path: "{{ lavarel_configure_env }}"
    regexp: '^DB_USERNAME=.*$'
    line: "DB_PORT={{ lavarel_configure_db_username }}"
  tags:
    - setup
    - configuration

- name: role_lavarel > configure the database password
  lineinfile:
    path: "{{ lavarel_configure_env }}"
    regexp: '^DB_PASSWORD=.*$'
    line: "DB_PORT={{ lavarel_configure_db_password }}"
  tags:
    - setup
    - configuration
